// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: getfeednamebyid.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFeedNameById = `-- name: GetFeedNameById :many
SELECT feeds.name AS Feedname FROM feed_follows
	INNER JOIN users ON users.id = feed_follows.user_id
	INNER JOIN feeds ON feeds.id = feed_follows.feed_id
	WHERE feed_follows.user_id = $1
`

func (q *Queries) GetFeedNameById(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getFeedNameById, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var feedname string
		if err := rows.Scan(&feedname); err != nil {
			return nil, err
		}
		items = append(items, feedname)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
