// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: removefeed.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const removeFeed = `-- name: RemoveFeed :one
DELETE FROM feed_follows
	WHERE feed_id = $1 AND user_id = $2
	RETURNING id, created_at, updated_at, user_id, feed_id
`

type RemoveFeedParams struct {
	FeedID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RemoveFeed(ctx context.Context, arg RemoveFeedParams) (FeedFollow, error) {
	row := q.db.QueryRowContext(ctx, removeFeed, arg.FeedID, arg.UserID)
	var i FeedFollow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}
